language: common-lisp
sudo: yes

env:
  matrix:
    - LISP=sbcl COVERALLS=true

install:
  # Install cl-travis.
  - curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | bash

before_script:
  - git clone https://github.com/fukamachi/cl-coveralls ~/lisp/cl-coveralls

script:
  - cl -l prove -l cl-coveralls
       -e '(or (coveralls:with-coveralls (:exclude (list "t"))
                 (prove:run :renki-test))
               (uiop:quit -1))'
